### PR TITLE
fixed loading examples does not reset spec 

### LINKED ISSUE #175: Loading spec doesn't set editor content
As you can see in the example below, I am editing the spec in the editor but it doesn't reset the spec when I load the example again. 

editor

### PR DESCRIPTION
**Pull request by starry97**
fixed #175

### CODE REVIEW

File: src/reducers/app/index.js [hunk 1]
```diff
@@ -75,15 +75,17 @@ export default (state = {
         return Object.assign({}, state, {
           error: e.message,
           editorString: JSON3.stringify(spec, null, 2, 60),
-          warningsLogger: logger
+          warningsLogger: logger,
+          selectedExample: 'vega-edited'
```
Comment (domoritz) [inline src/reducers/app/index.js]: Why not set to null?

**Comment by domoritz** [comment]
When there is an error in the spec, the spec completely disappears. Can you rebase this branch?
