### PR TITLE
fixed warnings do not reset after changing spec

### LINKED ISSUE #196: Warnings don't reset after changing spec
warning-bug

### PR DESCRIPTION
**Pull request by starry97**
fixed #196

### CODE REVIEW

File: src/reducers/index.js [hunk 1]
```diff
@@ -51,43 +51,29 @@ export default (state = DEFAULT_STATE, action) => {
       });
     }
     case SET_VEGA_EXAMPLE:
-      try {
```
Comment (starry97) [inline src/reducers/index.js:54]: I removed the try catch because SET_VEGA_EXAMPLE or SET_VEGA_LITE_EXAMPLE shouldn't have any errors or warnings
