### PR TITLE
fixed reset spec in manual mode

### LINKED ISSUE #180: Opening detail panel resets spec
If I am in manual mode, edit the spec, and then open the vega panel before parsing, my changes disappear.

### PR DESCRIPTION
**Pull request by starry97**
fixed #180

### CODE REVIEW

File: src/components/app.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ class App extends React.Component {
       console.log('[Vega-Editor] Received Message', evt.origin, data);
       // send acknowledgement
       var parsed = JSON.parse(data.spec);
-      data.spec = JSON.stringify(parsed, null, 2);
+      data.spec = JSON.stringify(parsed);
```
Comment (domoritz) [inline src/components/app.js]: Why this?

File: src/reducers/app/index.js [hunk 2]
```diff
@@ -81,7 +82,7 @@ export default (state = {
       return Object.assign({}, state, {
         vegaSpec: spec,
         mode: MODES.Vega,
-        editorString: action.spec,
+        editorString: JSON3.stringify(spec, null, 2, 60),
```
Comment (domoritz) [inline src/reducers/app/index.js]: I don't like this because this means we always format the spec. We actually hand format the specs for vega-lite.

File: src/components/app.js (hunk 1 above)
Comment (starry97) [reply src/components/app.js]: Since the spec is formatted in `updateVegaSpec` or `updateVegaLiteSpec`, it doesn't matter if we format it here or not. 
I'm not sure why the code here parses the spec then stringifys it, I think we should just remove
```javascript
var parsed = JSON.parse(data.spec);
data.spec = JSON.stringify(parsed);
```

**Comment by domoritz** [comment]
This works for now but it's a bit of a hack since in auto mode, the same problem exists but it's hidden because autoparsing is fast.
